### PR TITLE
Update Helm chart to support k8s 1.22

### PR DESCRIPTION
**Pull request by guidoiaquinti**
## Description
With https://github.com/PostHog/charts-clickhouse/pull/205 we removed the last roadblock to support Kubernetes version 1.22

This PR enables integration testing against this version and also update the chart metadata. 

## Type of change
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

## How has this been tested?
CI should be passing.

## Checklist
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by tiina303 — APPROVED** [review]
LGTM

**Review by fuziontech — APPROVED** [review]

**Comment by hazzadous** [comment]
Have kicked off the failing jobs 🤞

**Comment by hazzadous** [comment]
Fyi I added https://github.com/PostHog/charts-clickhouse/pull/220 for debugging

Looks like there might be some issues with ingress: https://github.com/PostHog/charts-clickhouse/runs/4461381717?check_suite_focus=true

**Comment by guidoiaquinti** [comment]
Thank you @hazzadous ! Yeah, I missed that we need to update the Helm dependency `ingress-nginx` to version >= 4:

> Ingress resources evolved over time. They started with apiVersion: extensions/v1beta1, then moved to apiVersion: networking.k8s.io/v1beta1 and more recently to apiVersion: networking.k8s.io/v1.
> 
> Here is how these Ingress versions are supported in Kubernetes: - before Kubernetes 1.19, only v1beta1 Ingress resources are supported - from Kubernetes 1.19 to 1.21, both v1beta1 and v1 Ingress resources are supported - in Kubernetes 1.22 and above, only v1 Ingress resources are supported
> 
> And here is how these Ingress versions are supported in NGINX Ingress Controller: - before version 1.0, only v1beta1 Ingress resources are supported - in version 1.0 and above, only v1 Ingress resources are
> 
> As a result, if you're running Kubernetes 1.19 or later, you should be able to use the latest version of the NGINX Ingress Controller; but if you're using an old version of Kubernetes (1.18 or earlier) you will have to use version 0.X of the NGINX Ingress Controller (e.g. version 0.49).
> 
> The Helm chart of the NGINX Ingress Controller switched to version 1 in version 4 of the chart. In other words, if you're running Kubernetes 1.19 or earlier, you should use version 3.X of the chart (this can be done by adding --version='<4' to the helm install command).
>
> ref: https://kubernetes.github.io/ingress-nginx/deploy/#running-on-kubernetes-versions-older-than-119

**Comment by guidoiaquinti** [comment]
We also need to update `cert-manager` from the current version `1.2.0` to _at least_ `1.5` (see [here](https://cert-manager.io/docs/installation/supported-releases/))

**Pull request merged**
