### PR TITLE
ci(k6s): remove flaky pluginEvent test

### PR DESCRIPTION
**Pull request by hazzadous**
To get to a point we can use tests as a merge condition, I'm disabling
this test.

## Type of change
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by guidoiaquinti — APPROVED** [review]

**Comment by guidoiaquinti** [comment]
cc @tiina303 @yakkomajuri @macobo can you suggest a better way to test e2e ingestion _post-buffer_?

**Comment by macobo** [comment]
I'll take a look tomorrow but have you tried `CONVERSION_BUFFER_ENABLED` env var which would disable the conversion buffer?

**Comment by hazzadous** [comment]
> I'll take a look tomorrow but have you tried CONVERSION_BUFFER_ENABLED env var which would disable the conversion buffer?

No, will give it a go separately from this PR.

**Comment by guidoiaquinti** [comment]
> I'll take a look tomorrow but have you tried `CONVERSION_BUFFER_ENABLED` env var which would disable the conversion buffer?

We can try that but I think it could be nice to have an e2e test with buffer enabled (as it should be the default moving on?)

**Comment by tiina303** [comment]
> We can try that but I think it could be nice to have an e2e test with buffer enabled (as it should be the default moving on?)

How about setting `BUFFER_CONVERSION_SECONDS = 1`

**Comment by macobo** [comment]
I'd say setting conversion buffer for this test was incidental - we already have extensive test coverage for it in the core repo, if we wanted it here we should have a separate test rather than overload the main one.

Note that the conversion buffer applies to ~0.3% of events in the wild.

**Pull request merged**
