### PR TITLE
Make ingress k8s 1.22 compatible

### PR DESCRIPTION
**Pull request by tiina303**
Part 1 for https://github.com/PostHog/charts-clickhouse/issues/117

Based on https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122

Verified:
1. nothing changes for pre 1.19 folks (changed the comparison to be to 27 to generate an v1beta file locally, the output was identical to prior to this PR via `helm template posthog charts/posthog --set cloud=na | grep "ingress.yaml" -A50`)
2. deployed to DigitalOcean, where I have k8s v1.21.3 (i.e. >19) & verified that I can still access the UI & see events.

### CODE REVIEW

**Comment by fuziontech** [comment]
Is the test broken for `v1.21`?

**Comment by tiina303** [comment]
> Is the test broken for v1.21?

on the rerun - before only 1.18 failed ... they are a bit flaky =(

**Review by fuziontech — APPROVED** [review]
🚢

**Comment by tiina303** [comment]
ticket for the flakiness https://github.com/PostHog/charts-clickhouse/issues/124

**Pull request merged**
