### PR TITLE
Grafana - add PostgreSQL dashboard

### PR DESCRIPTION
**Pull request by guidoiaquinti**
## Description
This PR adds a built-in dashboard for PostgreSQL and introduces minor edits to the Redis one.

More will follow. 

## Type of change
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

## How has this been tested?
Tested locally

## Checklist
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by hazzadous** [comment]
Let me spin up something locally and have a look

**Comment by guidoiaquinti** [comment]
> Let me spin up something locally and have a look

```
helm upgrade --install --set "cloud=private" --set "prometheus.enabled=true" --set "grafana.enabled=true" --set "prometheus-postgres-exporter.enabled=true" -f ./charts/posthog/values.yaml --timeout 30m --create-namespace --namespace posthog posthog ./charts/posthog --wait --wait-for-jobs --debug
```
should setup everything you need

**Comment by guidoiaquinti** [comment]
Here's also a screenshot
Screenshot 2022-03-01 at 11 47 11

**Review by hazzadous — APPROVED** [review]
Looks good

1. didn't see anything on redis board
2. future addition: pgbouncer has some stats also, e.g. maxwait
3. the default database is postgres, should this be posthog?

Screenshot 2022-03-01 at 10 58 33
Screenshot 2022-03-01 at 10 59 14

**Comment by guidoiaquinti** [comment]
> didn't see anything on redis board

For Redis you need `--set "prometheus-redis-exporter.enabled=true"`. 

> future addition: pgbouncer has some stats also, e.g. maxwait

Yes, we need to add a dashboard for it too (it's in the TODO list)

> the default database is postgres, should this be posthog?

We can technically hardcode it directly in the metrics if we want.

**Pull request merged**
