### PR TITLE
allow for disabling pgbouncer

### PR DESCRIPTION
**Pull request by DavidSpek**
Fixes: https://github.com/PostHog/charts-clickhouse/issues/280
## Description
This PR allows for disabling pgbouncer or configuring that an external postgres instance is using pgbouncer. It also makes is easier for people using external postgres to set the SSL mode for PostHog to connect to the database. Furthermore, it configures the init container to always check access to the database since this was originally handled by pgbouncer which can now be disabled properly.

## Type of change
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204767834161187

### CODE REVIEW

**Comment by DavidSpek** [comment]
Friendly ping @xvello.

**Comment by xvello** [comment]
Hello @DavidSpek, as stated in https://posthog.com/blog/sunsetting-helm-support-posthog we don't support this chart anymore, and are currently moving our Cloud regions away from it. We have stopped testing new changes against other deployment topologies than our Cloud regions, so I would not recommend running any revision of this chart released after May 31st.

Given that context, we will not review any PR or issue on this repository. I'll make sure the repository's readme reflects that situation.

**Comment by DavidSpek** [comment]
@xvello Are there any plans for a community managed helm chart? We at [Plural](https://www.plural.sh/) are currently using this helm chart for the PostHog deployment on our marketplace, and while we can maintain a chart ourselves I find it usually better if there is some form of "official" upstream chart even if it is maintained by the community.

**Comment by xvello** [comment]
Hello @DavidSpek, we currently have no plans to provide support for a community chart, but you are welcome to fork version 30.3.0 and start a community effort. I expect us to archive this repository in a couple of months, after we finish migrating our Cloud regions to more focused, cloud-only charts.

Please note that one of our reasons for sunsetting support of self-deploying the chart is the amount of tech debt that we incurred by supporting so many deployment topologies. We are currently working on paying back some of that debt to improve our systems’ reliability and efficiency. This means that the following months will bring breaking changes and deprecations, to allow us to ship future features faster and more safely.

**Comment by DavidSpek** [comment]
@xvello Forgive me if I was unclear. What I meant was if it would be an option to have this repo be maintain and managed by the community, or that a separate GitHub organization is created for community contributions that PostHog sends users to. This way PostHog doesn't need to support it at all, but the already established community using and contributing to this helm chart can continue without interruption.

**Pull request closed without merging**
