### PR TITLE
Bump default version SHA

### PR DESCRIPTION
**Pull request by macobo**
See issue https://github.com/PostHog/product-internal/issues/114 for context.

### CODE REVIEW

**Comment by fuziontech** [comment]
I looked into PostHog/product-internal#114 and there's a lot going on with nothing specific to a fix. What does this bake into the default deploy?

Is it mainly this PR? https://github.com/PostHog/posthog/pull/5355

**Comment by macobo** [comment]
> nothing specific to a fix.

See the linked PRs under the issue around fixing a regression at minimum contributing to the issue/causing data issues and other PR making the reads consistent again.

**Comment by fuziontech** [comment]
Sorry, I didn't mean that I saw no fixes. There were just a lot of reverts and the specific thing you wanted to ship here was not clear to me. Your last comment was still not clear to me but I'm pretty certain that the change you want to ship here is PostHog/posthog#5355 which looks good to me. Let me know if I'm mistaken here!

**Review by fuziontech — APPROVED** [review]
lgtm!

**Pull request merged**
